//GENERIC PRINT STATEMENTS
console.log("HELLO SHIVANI!!");
//DEBUGGING & LOGGING
console.error("NOT WORKING");
console.warn("NEED TO CHNAGE");
console.info("HEY PLEASE FOLLOW THIS BRFORE ENETERING ANY INPUT");